# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicApp(object):
    def setupUi(self, MusicApp):
        MusicApp.setObjectName("MusicApp")
        MusicApp.resize(880, 550)
        MusicApp.setMinimumSize(QtCore.QSize(880, 550))
        MusicApp.setMaximumSize(QtCore.QSize(880, 550))
        self.centralwidget = QtWidgets.QWidget(MusicApp)
        self.centralwidget.setObjectName("centralwidget")
        self.background_img = QtWidgets.QLabel(self.centralwidget)
        self.background_img.setGeometry(QtCore.QRect(0, 0, 881, 551))
        self.background_img.setText("")
        self.background_img.setPixmap(QtGui.QPixmap("utils/bg_imgs/bg_0006_9.jpg"))
        self.background_img.setScaledContents(True)
        self.background_img.setObjectName("background_img")
        self.overlay_img = QtWidgets.QLabel(self.centralwidget)
        self.overlay_img.setGeometry(QtCore.QRect(-30, 0, 931, 561))
        self.overlay_img.setText("")
        self.overlay_img.setPixmap(QtGui.QPixmap("utils/bg_imgs/bg_overlay.png"))
        self.overlay_img.setScaledContents(True)
        self.overlay_img.setObjectName("overlay_img")
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        self.title_frame.setGeometry(QtCore.QRect(10, 0, 861, 51))
        self.title_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.app_img = QtWidgets.QLabel(self.title_frame)
        self.app_img.setGeometry(QtCore.QRect(10, 0, 41, 41))
        self.app_img.setText("")
        self.app_img.setPixmap(QtGui.QPixmap(":/img/utils/images/app_img.png"))
        self.app_img.setScaledContents(True)
        self.app_img.setObjectName("app_img")
        self.title_label = QtWidgets.QLabel(self.title_frame)
        self.title_label.setGeometry(QtCore.QRect(70, 0, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("\n"
"color: rgb(170, 85, 255);")
        self.title_label.setObjectName("title_label")
        self.minimize_btn = QtWidgets.QPushButton(self.title_frame)
        self.minimize_btn.setGeometry(QtCore.QRect(780, 10, 41, 31))
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,0);\n"
"border-style:inset;\n"
"}\n"
"")
        self.minimize_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/utils/images/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_btn.setIcon(icon)
        self.minimize_btn.setIconSize(QtCore.QSize(24, 24))
        self.minimize_btn.setObjectName("minimize_btn")
        self.close_btn = QtWidgets.QPushButton(self.title_frame)
        self.close_btn.setGeometry(QtCore.QRect(820, 10, 41, 31))
        self.close_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color:rgba(255,128,128,110);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,0);\n"
"border-style:inset;\n"
"}\n"
"")
        self.close_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/utils/images/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_btn.setIcon(icon1)
        self.close_btn.setIconSize(QtCore.QSize(24, 24))
        self.close_btn.setObjectName("close_btn")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 331, 301))
        self.frame.setStyleSheet("background-color:rgba(0,0,0,130);\n"
"border-radius:15px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.song_label = QtWidgets.QLabel(self.frame)
        self.song_label.setGeometry(QtCore.QRect(0, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.song_label.setFont(font)
        self.song_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.song_label.setStyleSheet("color:white;")
        self.song_label.setAlignment(QtCore.Qt.AlignCenter)
        self.song_label.setObjectName("song_label")
        self.artist_label = QtWidgets.QLabel(self.frame)
        self.artist_label.setGeometry(QtCore.QRect(0, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.artist_label.setFont(font)
        self.artist_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.artist_label.setStyleSheet("color:white;")
        self.artist_label.setAlignment(QtCore.Qt.AlignCenter)
        self.artist_label.setObjectName("artist_label")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 71, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/img/utils/images/dialog-music.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.songName_label = QtWidgets.QLabel(self.frame)
        self.songName_label.setGeometry(QtCore.QRect(0, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.songName_label.setFont(font)
        self.songName_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.songName_label.setStyleSheet("color:white;")
        self.songName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.songName_label.setObjectName("songName_label")
        self.artisName_label = QtWidgets.QLabel(self.frame)
        self.artisName_label.setGeometry(QtCore.QRect(0, 180, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.artisName_label.setFont(font)
        self.artisName_label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.artisName_label.setStyleSheet("color:white;")
        self.artisName_label.setAlignment(QtCore.Qt.AlignCenter)
        self.artisName_label.setObjectName("artisName_label")
        self.addFavourites_btn = QtWidgets.QPushButton(self.frame)
        self.addFavourites_btn.setGeometry(QtCore.QRect(10, 230, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addFavourites_btn.setFont(font)
        self.addFavourites_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addFavourites_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,128,128,255);\n"
"color:white\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/utils/images/like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFavourites_btn.setIcon(icon2)
        self.addFavourites_btn.setObjectName("addFavourites_btn")
        self.addPlaylist_btn = QtWidgets.QPushButton(self.frame)
        self.addPlaylist_btn.setGeometry(QtCore.QRect(190, 230, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.addPlaylist_btn.setFont(font)
        self.addPlaylist_btn.setStyleSheet("QPushButton{\n"
"background-color:rgb(27, 170, 80);\n"
"color:white\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/utils/images/music_list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addPlaylist_btn.setIcon(icon3)
        self.addPlaylist_btn.setObjectName("addPlaylist_btn")
        self.volume_slider = QtWidgets.QSlider(self.centralwidget)
        self.volume_slider.setGeometry(QtCore.QRect(90, 430, 81, 21))
        self.volume_slider.setMaximum(100)
        self.volume_slider.setProperty("value", 50)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.volumeValue_label = QtWidgets.QLabel(self.centralwidget)
        self.volumeValue_label.setGeometry(QtCore.QRect(190, 420, 71, 31))
        self.volumeValue_label.setStyleSheet("color:rgb(255,255,255)")
        self.volumeValue_label.setObjectName("volumeValue_label")
        self.volume_img = QtWidgets.QLabel(self.centralwidget)
        self.volume_img.setGeometry(QtCore.QRect(50, 430, 21, 21))
        self.volume_img.setText("")
        self.volume_img.setPixmap(QtGui.QPixmap(":/img/utils/images/music-voice.png"))
        self.volume_img.setScaledContents(True)
        self.volume_img.setObjectName("volume_img")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 370, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255,255,255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 460, 851, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(30, 21, 224, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previous_btn = QtWidgets.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setKerning(False)
        self.previous_btn.setFont(font)
        self.previous_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previous_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,100)\n"
"}")
        self.previous_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/utils/images/pre.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previous_btn.setIcon(icon4)
        self.previous_btn.setIconSize(QtCore.QSize(24, 24))
        self.previous_btn.setCheckable(False)
        self.previous_btn.setChecked(False)
        self.previous_btn.setObjectName("previous_btn")
        self.horizontalLayout.addWidget(self.previous_btn)
        self.playStop_btn = QtWidgets.QPushButton(self.frame_3)
        self.playStop_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playStop_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,100)\n"
"}")
        self.playStop_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/utils/images/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playStop_btn.setIcon(icon5)
        self.playStop_btn.setIconSize(QtCore.QSize(24, 24))
        self.playStop_btn.setCheckable(True)
        self.playStop_btn.setChecked(False)
        self.playStop_btn.setObjectName("playStop_btn")
        self.horizontalLayout.addWidget(self.playStop_btn)
        self.next_btn = QtWidgets.QPushButton(self.frame_3)
        self.next_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.next_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,100)\n"
"}")
        self.next_btn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/utils/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next_btn.setIcon(icon6)
        self.next_btn.setIconSize(QtCore.QSize(24, 24))
        self.next_btn.setCheckable(False)
        self.next_btn.setChecked(False)
        self.next_btn.setObjectName("next_btn")
        self.horizontalLayout.addWidget(self.next_btn)
        self.loop_btn = QtWidgets.QPushButton(self.frame_3)
        self.loop_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.loop_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,100)\n"
"}")
        self.loop_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/utils/images/loop-one.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loop_btn.setIcon(icon7)
        self.loop_btn.setIconSize(QtCore.QSize(24, 24))
        self.loop_btn.setCheckable(True)
        self.loop_btn.setChecked(False)
        self.loop_btn.setObjectName("loop_btn")
        self.horizontalLayout.addWidget(self.loop_btn)
        self.shuffle_btn = QtWidgets.QPushButton(self.frame_3)
        self.shuffle_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shuffle_btn.setStyleSheet("QPushButton{\n"
"background-color:rgba(255,255,255,0);\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,100)\n"
"}")
        self.shuffle_btn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/utils/images/play-random.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuffle_btn.setIcon(icon8)
        self.shuffle_btn.setIconSize(QtCore.QSize(24, 24))
        self.shuffle_btn.setCheckable(True)
        self.shuffle_btn.setChecked(False)
        self.shuffle_btn.setObjectName("shuffle_btn")
        self.horizontalLayout.addWidget(self.shuffle_btn)
        self.musi_slider = QtWidgets.QSlider(self.frame_2)
        self.musi_slider.setGeometry(QtCore.QRect(320, 30, 361, 22))
        self.musi_slider.setStyleSheet("QSlider::groove:horizontal{\n"
"border: 1px solid #999999;\n"
"height: 15px;\n"
"padding:3px;\n"
"background:rgba(171, 171, 171,100);\n"
"margin:2px 0;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal{\n"
"background:rgb(0,0,50);\n"
"border:1px solid #5c5c5c;\n"
"width:10px;\n"
"border-radius:5px;\n"
"margin:-2px 0;\n"
"}")
        self.musi_slider.setOrientation(QtCore.Qt.Horizontal)
        self.musi_slider.setObjectName("musi_slider")
        self.time_label = QtWidgets.QLabel(self.frame_2)
        self.time_label.setGeometry(QtCore.QRect(690, 30, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("color:white;")
        self.time_label.setScaledContents(False)
        self.time_label.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.time_label.setObjectName("time_label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(360, 70, 501, 361))
        self.stackedWidget.setStyleSheet("background-color:rgba(0,0,0,50);\n"
"border-radius:10px;\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.songList_page = QtWidgets.QWidget()
        self.songList_page.setObjectName("songList_page")
        self.label_3 = QtWidgets.QLabel(self.songList_page)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color:rgb(170, 255, 127)")
        self.label_3.setObjectName("label_3")
        self.loadedSong_listWidget = QtWidgets.QListWidget(self.songList_page)
        self.loadedSong_listWidget.setGeometry(QtCore.QRect(40, 70, 441, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loadedSong_listWidget.setFont(font)
        self.loadedSong_listWidget.setStyleSheet("color:white;\n"
"background-color:rgba(0,0,0,100);\n"
"\n"
"selection-background-color:rgb(255,144,64);\n"
"selection-color:rgb(86,227,194);\n"
"padding:10px;")
        self.loadedSong_listWidget.setObjectName("loadedSong_listWidget")
        self.frame_5 = QtWidgets.QFrame(self.songList_page)
        self.frame_5.setGeometry(QtCore.QRect(330, 10, 138, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addSong_btn = QtWidgets.QPushButton(self.frame_5)
        self.addSong_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.addSong_btn.setStyleSheet("background-color:rgb(255,255,255);")
        self.addSong_btn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/utils/images/addFromLocal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addSong_btn.setIcon(icon9)
        self.addSong_btn.setIconSize(QtCore.QSize(32, 32))
        self.addSong_btn.setObjectName("addSong_btn")
        self.horizontalLayout_2.addWidget(self.addSong_btn)
        self.deleteSong_btn = QtWidgets.QPushButton(self.frame_5)
        self.deleteSong_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.deleteSong_btn.setStyleSheet("background-color:rgb(255,255,255)")
        self.deleteSong_btn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/utils/images/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteSong_btn.setIcon(icon10)
        self.deleteSong_btn.setIconSize(QtCore.QSize(32, 32))
        self.deleteSong_btn.setObjectName("deleteSong_btn")
        self.horizontalLayout_2.addWidget(self.deleteSong_btn)
        self.clearSong_btn = QtWidgets.QPushButton(self.frame_5)
        self.clearSong_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.clearSong_btn.setStyleSheet("background-color:rgb(255,255,255)")
        self.clearSong_btn.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/img/utils/images/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearSong_btn.setIcon(icon11)
        self.clearSong_btn.setIconSize(QtCore.QSize(32, 32))
        self.clearSong_btn.setObjectName("clearSong_btn")
        self.horizontalLayout_2.addWidget(self.clearSong_btn)
        self.stackedWidget.addWidget(self.songList_page)
        self.playlist_page = QtWidgets.QWidget()
        self.playlist_page.setObjectName("playlist_page")
        self.label_4 = QtWidgets.QLabel(self.playlist_page)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("\n"
"color:rgb(170, 255, 127)")
        self.label_4.setObjectName("label_4")
        self.playlist_listWidget = QtWidgets.QListWidget(self.playlist_page)
        self.playlist_listWidget.setGeometry(QtCore.QRect(30, 70, 441, 241))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.playlist_listWidget.setFont(font)
        self.playlist_listWidget.setStyleSheet("color:white;\n"
"background-color:rgba(0,0,0,100);\n"
"\n"
"selection-background-color:rgb(255,144,64);\n"
"selection-color:rgb(86,227,194);\n"
"padding:10px;")
        self.playlist_listWidget.setObjectName("playlist_listWidget")
        self.loadSelected_btn = QtWidgets.QPushButton(self.playlist_page)
        self.loadSelected_btn.setGeometry(QtCore.QRect(310, 20, 151, 30))
        self.loadSelected_btn.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.loadSelected_btn.setFont(font)
        self.loadSelected_btn.setStyleSheet("background-color:rgb(42, 176, 85);\n"
"color:white")
        self.loadSelected_btn.setIconSize(QtCore.QSize(32, 32))
        self.loadSelected_btn.setObjectName("loadSelected_btn")
        self.newPlaylist_btn = QtWidgets.QPushButton(self.playlist_page)
        self.newPlaylist_btn.setGeometry(QtCore.QRect(20, 320, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.newPlaylist_btn.setFont(font)
        self.newPlaylist_btn.setStyleSheet("background-color:white;\n"
"border-radius:10px;\n"
"color:purple;")
        self.newPlaylist_btn.setObjectName("newPlaylist_btn")
        self.removeSelectedPlaylist_btn = QtWidgets.QPushButton(self.playlist_page)
        self.removeSelectedPlaylist_btn.setGeometry(QtCore.QRect(180, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.removeSelectedPlaylist_btn.setFont(font)
        self.removeSelectedPlaylist_btn.setStyleSheet("background-color:white;\n"
"border-radius:10px;\n"
"color:purple;")
        self.removeSelectedPlaylist_btn.setObjectName("removeSelectedPlaylist_btn")
        self.removeAllPlaylist_btn = QtWidgets.QPushButton(self.playlist_page)
        self.removeAllPlaylist_btn.setGeometry(QtCore.QRect(340, 320, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.removeAllPlaylist_btn.setFont(font)
        self.removeAllPlaylist_btn.setStyleSheet("background-color:white;\n"
"border-radius:10px;\n"
"color:purple;")
        self.removeAllPlaylist_btn.setObjectName("removeAllPlaylist_btn")
        self.stackedWidget.addWidget(self.playlist_page)
        self.favourites_page = QtWidgets.QWidget()
        self.favourites_page.setObjectName("favourites_page")
        self.deleteSelected_btn = QtWidgets.QPushButton(self.favourites_page)
        self.deleteSelected_btn.setGeometry(QtCore.QRect(360, 20, 41, 30))
        self.deleteSelected_btn.setMinimumSize(QtCore.QSize(30, 30))
        self.deleteSelected_btn.setStyleSheet("background-color:rgb(255,255,255)")
        self.deleteSelected_btn.setText("")
        self.deleteSelected_btn.setIcon(icon10)
        self.deleteSelected_btn.setIconSize(QtCore.QSize(32, 32))
        self.deleteSelected_btn.setObjectName("deleteSelected_btn")
        self.clearAll_btn_ = QtWidgets.QPushButton(self.favourites_page)
        self.clearAll_btn_.setGeometry(QtCore.QRect(420, 20, 41, 30))
        self.clearAll_btn_.setMinimumSize(QtCore.QSize(30, 30))
        self.clearAll_btn_.setStyleSheet("background-color:rgb(255,255,255)")
        self.clearAll_btn_.setText("")
        self.clearAll_btn_.setIcon(icon11)
        self.clearAll_btn_.setIconSize(QtCore.QSize(32, 32))
        self.clearAll_btn_.setObjectName("clearAll_btn_")
        self.favouritesSong_listWidget = QtWidgets.QListWidget(self.favourites_page)
        self.favouritesSong_listWidget.setGeometry(QtCore.QRect(40, 70, 441, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.favouritesSong_listWidget.setFont(font)
        self.favouritesSong_listWidget.setStyleSheet("color:white;\n"
"background-color:rgba(0,0,0,100);\n"
"\n"
"selection-background-color:rgb(255,144,64);\n"
"selection-color:rgb(86,227,194);\n"
"padding:10px;")
        self.favouritesSong_listWidget.setObjectName("favouritesSong_listWidget")
        self.label_6 = QtWidgets.QLabel(self.favourites_page)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("\n"
"color:rgb(170, 255, 127)")
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.favourites_page)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(360, 440, 491, 41))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.songList_btn = QtWidgets.QPushButton(self.frame_4)
        self.songList_btn.setGeometry(QtCore.QRect(10, 0, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.songList_btn.setFont(font)
        self.songList_btn.setStyleSheet("background-color:rgb(170, 0, 255);\n"
"color:white;\n"
"border-radius:15px;")
        self.songList_btn.setObjectName("songList_btn")
        self.playlist_btn = QtWidgets.QPushButton(self.frame_4)
        self.playlist_btn.setGeometry(QtCore.QRect(180, 0, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.playlist_btn.setFont(font)
        self.playlist_btn.setStyleSheet("background-color:rgb(27, 170, 80);\n"
"color:white;\n"
"border-radius:15px;")
        self.playlist_btn.setObjectName("playlist_btn")
        self.favourites_btn = QtWidgets.QPushButton(self.frame_4)
        self.favourites_btn.setGeometry(QtCore.QRect(350, 0, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.favourites_btn.setFont(font)
        self.favourites_btn.setStyleSheet("background-color:rgba(255,128,128,255);\n"
"color:white;\n"
"border-radius:15px;")
        self.favourites_btn.setObjectName("favourites_btn")
        self.background_img.raise_()
        self.overlay_img.raise_()
        self.title_frame.raise_()
        self.frame.raise_()
        self.volume_slider.raise_()
        self.volumeValue_label.raise_()
        self.volume_img.raise_()
        self.label.raise_()
        self.stackedWidget.raise_()
        self.frame_4.raise_()
        self.frame_2.raise_()
        MusicApp.setCentralWidget(self.centralwidget)
        self.actionPlay = QtWidgets.QAction(MusicApp)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause_Unpause = QtWidgets.QAction(MusicApp)
        self.actionPause_Unpause.setObjectName("actionPause_Unpause")
        self.actionNext = QtWidgets.QAction(MusicApp)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MusicApp)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionStop = QtWidgets.QAction(MusicApp)
        self.actionStop.setObjectName("actionStop")
        self.actionAdd_Select_To_Favourites = QtWidgets.QAction(MusicApp)
        self.actionAdd_Select_To_Favourites.setObjectName("actionAdd_Select_To_Favourites")
        self.actionAdd_All_To_Favourites = QtWidgets.QAction(MusicApp)
        self.actionAdd_All_To_Favourites.setObjectName("actionAdd_All_To_Favourites")
        self.actionLoad_Selected_Playlist = QtWidgets.QAction(MusicApp)
        self.actionLoad_Selected_Playlist.setObjectName("actionLoad_Selected_Playlist")
        self.actionDelete_Selected_Playlist = QtWidgets.QAction(MusicApp)
        self.actionDelete_Selected_Playlist.setObjectName("actionDelete_Selected_Playlist")
        self.actionDelete_All_Playlists = QtWidgets.QAction(MusicApp)
        self.actionDelete_All_Playlists.setObjectName("actionDelete_All_Playlists")
        self.actionRemove_Selected_Favourites = QtWidgets.QAction(MusicApp)
        self.actionRemove_Selected_Favourites.setObjectName("actionRemove_Selected_Favourites")
        self.actionRemove_All_Favourites = QtWidgets.QAction(MusicApp)
        self.actionRemove_All_Favourites.setObjectName("actionRemove_All_Favourites")
        self.actionSave_Selected_To_A_Playlist = QtWidgets.QAction(MusicApp)
        self.actionSave_Selected_To_A_Playlist.setObjectName("actionSave_Selected_To_A_Playlist")
        self.actionSave_All_To_A_Playlist = QtWidgets.QAction(MusicApp)
        self.actionSave_All_To_A_Playlist.setObjectName("actionSave_All_To_A_Playlist")

        self.retranslateUi(MusicApp)
        self.stackedWidget.setCurrentIndex(1)
        self.close_btn.clicked.connect(MusicApp.close) # type: ignore
        self.minimize_btn.clicked.connect(MusicApp.showMinimized) # type: ignore
        self.volume_slider.valueChanged['int'].connect(self.volumeValue_label.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MusicApp)

    def retranslateUi(self, MusicApp):
        _translate = QtCore.QCoreApplication.translate
        MusicApp.setWindowTitle(_translate("MusicApp", "EchoSync >_< v. 1.0.0"))
        self.title_label.setText(_translate("MusicApp", "EchoSync"))
        self.label_2.setText(_translate("MusicApp", "What\'s playing?"))
        self.song_label.setText(_translate("MusicApp", "Song"))
        self.artist_label.setText(_translate("MusicApp", "Artist"))
        self.songName_label.setText(_translate("MusicApp", "Name of the song"))
        self.artisName_label.setText(_translate("MusicApp", "Name of the artist"))
        self.addFavourites_btn.setText(_translate("MusicApp", "Add to Favourites"))
        self.addPlaylist_btn.setText(_translate("MusicApp", "Add to Playlist"))
        self.volumeValue_label.setText(_translate("MusicApp", "50/100"))
        self.label.setText(_translate("MusicApp", "Volume"))
        self.time_label.setText(_translate("MusicApp", "00:00:00 / 00:00:00"))
        self.label_3.setText(_translate("MusicApp", "Song List"))
        self.label_4.setText(_translate("MusicApp", "Playlist\'s"))
        self.loadSelected_btn.setText(_translate("MusicApp", "Load Selected"))
        self.newPlaylist_btn.setText(_translate("MusicApp", "Create Playlist"))
        self.removeSelectedPlaylist_btn.setText(_translate("MusicApp", "Remove Selected"))
        self.removeAllPlaylist_btn.setText(_translate("MusicApp", "Remove All"))
        self.label_6.setText(_translate("MusicApp", "Favourites"))
        self.songList_btn.setText(_translate("MusicApp", "Songs"))
        self.playlist_btn.setText(_translate("MusicApp", "Playlist\'s"))
        self.favourites_btn.setText(_translate("MusicApp", "Favourites"))
        self.actionPlay.setText(_translate("MusicApp", "Play"))
        self.actionPlay.setToolTip(_translate("MusicApp", "Play"))
        self.actionPause_Unpause.setText(_translate("MusicApp", "Pause_Unpause"))
        self.actionPause_Unpause.setToolTip(_translate("MusicApp", "Pause/Unpause"))
        self.actionNext.setText(_translate("MusicApp", "Next"))
        self.actionNext.setToolTip(_translate("MusicApp", "Next"))
        self.actionPrevious.setText(_translate("MusicApp", "Previous"))
        self.actionPrevious.setToolTip(_translate("MusicApp", "Previous"))
        self.actionStop.setText(_translate("MusicApp", "Stop"))
        self.actionStop.setToolTip(_translate("MusicApp", "Stop"))
        self.actionAdd_Select_To_Favourites.setText(_translate("MusicApp", "Add_Select_To_Favourites"))
        self.actionAdd_Select_To_Favourites.setToolTip(_translate("MusicApp", "Add Select To Favourites"))
        self.actionAdd_All_To_Favourites.setText(_translate("MusicApp", "Add_All_To_Favourites"))
        self.actionAdd_All_To_Favourites.setToolTip(_translate("MusicApp", "Add All To Favourites"))
        self.actionLoad_Selected_Playlist.setText(_translate("MusicApp", "Load_Selected_Playlist"))
        self.actionLoad_Selected_Playlist.setToolTip(_translate("MusicApp", "Loadm Selected Playlist"))
        self.actionDelete_Selected_Playlist.setText(_translate("MusicApp", "Delete_Selected_Playlist"))
        self.actionDelete_Selected_Playlist.setToolTip(_translate("MusicApp", "Delete Selected Playlist"))
        self.actionDelete_All_Playlists.setText(_translate("MusicApp", "Delete_All_Playlists"))
        self.actionDelete_All_Playlists.setToolTip(_translate("MusicApp", "Delete All Playlists"))
        self.actionRemove_Selected_Favourites.setText(_translate("MusicApp", "Remove_Selected_Favourites"))
        self.actionRemove_Selected_Favourites.setToolTip(_translate("MusicApp", "Remove Selected Favourites"))
        self.actionRemove_All_Favourites.setText(_translate("MusicApp", "Remove_All_Favourites"))
        self.actionRemove_All_Favourites.setToolTip(_translate("MusicApp", "Remove All Favourites"))
        self.actionSave_Selected_To_A_Playlist.setText(_translate("MusicApp", "Save_Selected_To_A_Playlist"))
        self.actionSave_Selected_To_A_Playlist.setToolTip(_translate("MusicApp", "Save Selected To A Playlist"))
        self.actionSave_All_To_A_Playlist.setText(_translate("MusicApp", "Save_All_To_A_Playlist"))
        self.actionSave_All_To_A_Playlist.setToolTip(_translate("MusicApp", "Save All To A Playlist"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MusicApp = QtWidgets.QMainWindow()
    ui = Ui_MusicApp()
    ui.setupUi(MusicApp)
    MusicApp.show()
    sys.exit(app.exec_())
